association <- cbind(c("Aprostocetus_sp","Emersonella_albicoxa",
                       "Emersonella_carballoi",
                       "Emersonella_cuignetae_subtype1",
                       "Emersonella_horismenoides_sub1",
                       "Emersonella_niveipes_sub1",
                       "Emersonella_niveipes_sub1",
                       "Emersonella_niveipes_sub1", "Emersonella_nr_carballoi",
                       "Emersonella_nr_hastata", "Emersonella_planiceps_subtype1", 
                       "Emersonella_planiceps_subtype1",
                       "Emersonella_planiceps_subtype1",
                       "Emersonella_planiceps_subtype1","Emersonella_planiscuta"
                       ,"Emersonella_pubipennis_sub1",
                       "Emersonella_pubipennis_sub1","Emersonella_reticulata", 
                       "Emersonella_rotunda_subtype1", 
                       "Emersonella_rotunda_subtype2",
                       "Emersonella_rotunda_subtype2",
                       "Emersonella_rotunda_subtype2",
                       "Emersonella_rotunda_subtype2", 
                       "Emersonella_rotunda_subtype2",
                       "Emersonella_rotunda_subtype3",
                       "Emersonella_rotunda_subtype3", 
                       "Emersonella_rotunda_subtype3",
                       "Emersonella_rotunda_subtype3",
                       "Emersonella_rotunda_subtype3",
                       "Emersonella_rotunda_subtype3", 
                       "Emersonella_rotunda_subtype3",
                       "Emersonella_rotunda_subtype4",
                       "Emersonella_rotunda_subtype5","Emersonella_species1",
                       "Emersonella_species2", "Emersonella_species3_subtype1",
                       "Emersonella_species3_subtype2", 
                       "Emersonella_species3_subtype1",
                       "Emersonella_species3_subtype2", "Emersonella_species4"
                       ,"Emersonella_tanigaster","Emersonella_varicolor",
                       "Emersonella_windsori", "Horismenus_species1",
                       "Horismenus_species2", "Horismenus_species3",
                       "Horismenus_species5", "Horismenus_species6", 
                       "Signiphoridae_species1"),
                     c("Discomorpha_salvini","Hilarocassis_evanida",
                       "Deloyala_guttata","Chelymorpha_alternans", 
                       "Cistudinella_foveolata", "Chelymorpha_alternans",
                       "Stolas_pictilis","Hilarocassis_evanida", 
                       "Xenocassis_ambita","Hybosa_mellicula", 
                       "Microctenochira_sp1","Microctenochira_sp2",
                       "Charidotella_sinuata",
                       "Charidotella_sexpunctata","Stolas_lebasii",
                       "Acromis_sparsa", "Paraselenis_tersa",
                       "Polychalma_multicava", "Agroiconota_propinqua",
                       "Charidotella_zona", "Charidotella_ventricosa", 
                       "Charidotella_proxima", "Charidotella_sexpunctata", 
                       "Charidotella_sinuata", "Microctenochira_sp1",
                       "Microctenochira_sp2", "Microctenochira_cumulata",
                       "Microctenochira_nr_nigrocincta", 
                       "Microctenochira_flavonotata", 
                       "Microctenochira_nigrocincta", 
                       "Microctenochira_fraterna", "Deloyala_guttata", 
                       "Charidotis_vitreata", "Chelymorpha_alternans",
                       "Stolas_lebasii", "Deloyala_guttata",
                       "Metrionella_erratica",
                       "Metrionella_erratica","Deloyala_guttata", 
                       "Cistudinella_foveolata", "Charidotis_abrupta",
                       "Tapinaspis_waesmali", "Omaspides_bistriata", 
                       "Polychalma_multicava", "Discomorpha_salvini",
                       "Discomorpha_salvini", "Spaethiella_species",
                       "Spaethiella_species", "Charidotis_abrupta"
                       ))                              

